// Mirrors the `Role` enum in prisma/schema.prisma exactly. Keep in sync.
export enum Role {
  MEMBER = "MEMBER",
  MENTOR = "MENTOR",
  MODERATOR = "MODERATOR",
  SAFETY_MODERATOR = "SAFETY_MODERATOR",
  ADMIN = "ADMIN",
  SUPER_ADMIN = "SUPER_ADMIN",
}

export const ALL_ROLES: Role[] = [
  Role.MEMBER,
  Role.MENTOR,
  Role.MODERATOR,
  Role.SAFETY_MODERATOR,
  Role.ADMIN,
  Role.SUPER_ADMIN,
];

// Granular permissions. Deliberately fine-grained rather than "isAdmin" style
// booleans, so a role can be given exactly the access it needs and nothing
// more (product requirement: "Do not give every admin unrestricted access").
export enum Permission {
  // Own-account / own-data actions available to every authenticated member
  VIEW_OWN_PROFILE = "VIEW_OWN_PROFILE",
  EDIT_OWN_PROFILE = "EDIT_OWN_PROFILE",
  SEND_INTRODUCTION_REQUEST = "SEND_INTRODUCTION_REQUEST",
  SEND_MESSAGE = "SEND_MESSAGE",
  INITIATE_CALL = "INITIATE_CALL",
  FILE_REPORT = "FILE_REPORT",
  BLOCK_USER = "BLOCK_USER",
  INVITE_FAMILY_MENTOR = "INVITE_FAMILY_MENTOR",
  CREATE_COMMUNITY_POST = "CREATE_COMMUNITY_POST",
  REQUEST_MENTORSHIP = "REQUEST_MENTORSHIP",
  ORGANIZE_FUNDRAISER = "ORGANIZE_FUNDRAISER",
  DONATE = "DONATE",

  // Mentor-specific
  ACCEPT_MENTORSHIP_REQUEST = "ACCEPT_MENTORSHIP_REQUEST",
  VIEW_MENTEE_STAGE_SUMMARY = "VIEW_MENTEE_STAGE_SUMMARY",

  // Moderation (general — content-level, non-safety-critical)
  VIEW_REPORTED_CONTENT_METADATA = "VIEW_REPORTED_CONTENT_METADATA",
  REMOVE_COMMUNITY_CONTENT = "REMOVE_COMMUNITY_CONTENT",
  ISSUE_WARNING = "ISSUE_WARNING",
  RESOLVE_MODERATION_CASE = "RESOLVE_MODERATION_CASE",

  // Safety moderation (elevated — can access reported conversation content
  // via the escrow flow, suspend/ban accounts)
  ACCESS_REPORTED_CONVERSATION_CONTENT = "ACCESS_REPORTED_CONVERSATION_CONTENT",
  SUSPEND_ACCOUNT = "SUSPEND_ACCOUNT",
  BAN_ACCOUNT = "BAN_ACCOUNT",
  REINSTATE_ACCOUNT = "REINSTATE_ACCOUNT",
  ESCALATE_MODERATION_CASE = "ESCALATE_MODERATION_CASE",

  // Verification review
  REVIEW_IDENTITY_VERIFICATION = "REVIEW_IDENTITY_VERIFICATION",
  APPROVE_MENTOR_STATUS = "APPROVE_MENTOR_STATUS",

  // Community / events / jobs administration
  APPROVE_FUNDRAISING_CAMPAIGN = "APPROVE_FUNDRAISING_CAMPAIGN",
  APPROVE_FUND_DISBURSEMENT = "APPROVE_FUND_DISBURSEMENT",
  MANAGE_EVENTS = "MANAGE_EVENTS",
  MANAGE_JOBS = "MANAGE_JOBS",

  // Platform administration (restricted to ADMIN/SUPER_ADMIN)
  VIEW_AUDIT_LOG = "VIEW_AUDIT_LOG",
  ASSIGN_MODERATION_CASE = "ASSIGN_MODERATION_CASE",
  MANAGE_MODERATOR_ROLES = "MANAGE_MODERATOR_ROLES", // promote/demote MODERATOR, SAFETY_MODERATOR, MENTOR
  MANAGE_ADMIN_ROLES = "MANAGE_ADMIN_ROLES", // promote/demote ADMIN — SUPER_ADMIN only
  VIEW_PLATFORM_ANALYTICS = "VIEW_PLATFORM_ANALYTICS",
}
