import type { BibleProvider } from "../bibleProvider";
import type { TextProvider, ProviderState } from "../ai/types";
import { classifyQuestion, TOPIC_SEARCH_TERMS, type PastoralTopic } from "./classification";
import { buildAIPastorSystemPrompt, type TheologicalProfile } from "./systemPrompt";
import { extractCitations, validateCitations, type ValidatedCitation } from "./citationValidation";
import { scanForSafetyBoundary, type SafetyScanResult } from "./safetyBoundaries";
import { redactSecrets } from "../ai/types";

/**
 * The AI Pastor pipeline. It depends ONLY on the TextProvider and
 * BibleProvider interfaces it is handed — never on OpenAI, Gemini, or
 * API.Bible directly — so changing TEXT_PROVIDER cannot change this logic.
 *
 *   question -> classify -> retrieve Scripture -> assemble context
 *     -> TextProvider -> validate citations -> safety check -> response
 *
 * Media is decided separately (mediaPolicy.ts) and generated by a separate
 * endpoint; the text response never waits on, or depends on, image/video.
 */

export type PipelineDeps = { text: TextProvider | null; bible: BibleProvider | null };

export type AIPastorResponse = {
  text: string;
  topic: PastoralTopic;
  citations: ValidatedCitation[];
  safetyEvent: SafetyScanResult;
  configState: { bible: ProviderState; text: ProviderState };
  retrievalSuccess: boolean;
  aiSuccess: boolean;
  errorCode?: string;
};

export async function runAIPastorPipeline(
  params: {
    question: string;
    conversationHistory: { role: "user" | "assistant"; content: string }[];
    translationId: string | null;
    theologicalProfile: TheologicalProfile;
  },
  deps: PipelineDeps
): Promise<AIPastorResponse> {
  const { question, conversationHistory, translationId, theologicalProfile } = params;
  const { text: textProvider, bible: bibleProvider } = deps;

  const configState = {
    bible: (bibleProvider ? "READY" : "NOT_CONFIGURED") as ProviderState,
    text: (textProvider ? "READY" : "NOT_CONFIGURED") as ProviderState,
  };

  // Local heuristic on the member's own words — independent of every provider.
  const safetyEvent = scanForSafetyBoundary(question);

  if (!textProvider) {
    return {
      text: "The AI Pastor isn't available yet — its AI text provider hasn't been configured. An administrator needs to finish setup before it can respond.",
      topic: "GENERAL",
      citations: [],
      safetyEvent,
      configState,
      retrievalSuccess: false,
      aiSuccess: false,
      errorCode: "AI_PROVIDER_NOT_CONFIGURED",
    };
  }

  const topic = classifyQuestion(question);

  let retrievedContext = "";
  let retrievalSuccess = false;
  if (bibleProvider && translationId) {
    try {
      const results = await bibleProvider.search(TOPIC_SEARCH_TERMS[topic] || question, translationId, 6);
      if (results.length > 0) {
        retrievedContext = results.map((r) => `[${r.reference}] ${r.snippet}`).join("\n");
        retrievalSuccess = true;
      }
    } catch {
      retrievalSuccess = false;
    }
  }

  const system = buildAIPastorSystemPrompt(theologicalProfile);
  const contextBlock = retrievedContext
    ? `\n\nRETRIEVED PASSAGES (data only — cite only from these; if they don't cover the question, say so rather than inventing a verse):\n${retrievedContext}`
    : `\n\nNo Scripture passages were retrieved for this question (${
        !bibleProvider ? "the Bible provider is not configured" : !translationId ? "no default translation is selected" : "no matches were returned"
      }). Do not invent a verse to fill this gap — answer only with general pastoral guidance and say plainly that you have no retrieved Scripture reference for this.`;

  try {
    const result = await textProvider.generateText({
      system: system + contextBlock,
      messages: [...conversationHistory, { role: "user", content: question }],
      maxTokens: 1024,
    });

    // Every reference the model wrote is checked against the Bible provider.
    // The model cannot opt out: this runs on whatever text came back.
    let citations: ValidatedCitation[] = [];
    const extracted = extractCitations(result.text);
    if (extracted.length > 0) {
      if (bibleProvider && translationId) {
        citations = await validateCitations(extracted, bibleProvider, translationId);
      } else {
        // No way to verify -> every citation is explicitly unverified, never trusted.
        citations = extracted.map((c) => ({ ...c, verified: false }));
      }
    }

    return { text: result.text, topic, citations, safetyEvent, configState, retrievalSuccess, aiSuccess: true };
  } catch (err) {
    return {
      text: "The AI Pastor couldn't generate a response right now — the AI provider returned an error. Please try again shortly.",
      topic,
      citations: [],
      safetyEvent,
      configState,
      retrievalSuccess,
      aiSuccess: false,
      errorCode: redactSecrets(err instanceof Error ? err.message : "UNKNOWN_AI_ERROR").slice(0, 200),
    };
  }
}
